apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3-demo
  namespace: tesi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: test3-demo
  template:
    metadata:
      labels:
        app: test3-demo
    spec:
      containers:
        - name: springboot
          image: alessandroliviero/test3-demo:test3-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test3-demo
  namespace: tesi
spec:
  type: NodePort
  ports:
    - port: 80
      name: high
      protocol: TCP
      targetPort: 80
  selector:
    app: test3-demo
---
