version: '3'

services:
  jhooq-springboot-container:
    image: front-end-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/front-end-container
    ports:
      - "8080:8080"
