apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
  namespace: tesi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: jhooq-springboot
  template:
    metadata:
      labels:
        app: jhooq-springboot
    spec:
      containers:
        - name: springboot
          image: alessandroliviero/jhooq-docker-demo:jhooq-docker-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
  namespace: tesi
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: high
      protocol: TCP
      targetPort: 8080
  selector:
    app: jhooq-springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-test2
  namespace: tesi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: springboot-test2
  template:
    metadata:
      labels:
        app: springboot-test2
    spec:
      containers:
        - name: springboot-test2
          image: alessandroliviero/test2-docker-demo:test2-docker-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-test2
  namespace: tesi
spec:
  ports:
    - port: 8080
      name: high
      protocol: TCP
      targetPort: 8080
  selector:
    app: springboot-test2
  type: LoadBalancer
---
