apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
        - name: springboot
          image: alessandroliviero/test-docker-demo:test-docker-demo
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: test2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: test2
